# Generated by Django 2.2.24 on 2021-08-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_content_expiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentexpiry',
            options={'verbose_name': 'Content Expiry', 'verbose_name_plural': 'Content Expiry'},
        ),
        migrations.AlterField(
            model_name='contentexpiry',
            name='expires',
            field=models.DateTimeField(verbose_name='expiry date'),
        ),
    ]
