# Generated by Django 2.2.24 on 2021-09-22 09:12

from django.db import migrations, models
import django.db.models.deletion
import djangocms_content_expiry.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djangocms_content_expiry', '0002_default_expiry_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentExpiryContentTypeConfiguration',
            fields=[
                ('duration', models.IntegerField(help_text='duration in days')),
                ('content_type', models.OneToOneField(limit_choices_to=djangocms_content_expiry.models.limit_content_type_choices, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'Content Type Configuration',
                'verbose_name_plural': 'Content Type Configuration',
            },
        ),
    ]
